### PR TITLE
Make change propagation listener receive propagated changes

### PR DESCRIPTION
**Pull request by HeikoKlare**
This is preparatory work for removing the `PropagatedChangeListener` by integrating the required functionality into the `ChangePropagationListener` interface.

### CODE REVIEW

**Comment by JanWittler** [comment]
I am not sure if merging the two interfaces is the best approach to get rid of the `PropagatedChangeListener`.
Right now, we only use the `ChangePropagationListener` in two places:
1) In the `BasicView` to get notified when the view source changed. Here we only use the `finishedChangePropagation` method.
2) In the `Java2PCMTransformationTests` for our workaround to synchronise all changes. Here we use the `finished` and `aborted` methods.

Hence, our interface right now is already too wide as the `startedChangePropagation` method is never used. Therefore, I am not sure if we should extend the interface with a functionality we only need for an optional extension. (We could rather think about simplifying the interface to something like `ChangeableModelRepositoryObserver` with only one function `changeableModelRepositoryChanged(Exception optionalException)` or such.)

Another solution to getting rid of the `PropagatedChangeListener` would be to implement the change visualisation extension as a decorator for the `ChangeableModelRepository`. Here, we only need to override the `propagateChange` method to intercept the propagated changes from its decorated repository before returning them. This would not require to design our interfaces based on an optional extension.

**Comment by HeikoKlare** [comment]
I see your point, but I do not fully agree. The interface provides the functionality you can expect from its name. Since it is a listener implementation, you will not provide an interface that is actually required by someone, because a listener is supposed to be provided without knowing who may use it.

I also thought about providing the functionality for the visualization with a decorator, but actually the visualization listens to a V-SUM and its changes rather than intercepting the propagation. A decorator would require to break up the interaction of views and the V-SUM integrating the visualization, although it is actually supposed to only listen to changes without anyone taking notice of it.

**Comment by HeikoKlare** [comment]
As discussed, I have cleaned up the `ChangePropagationListener` interface by removing the abort case and adapted the `startedChangePropagation` method to also receive the change to propagate like the `finishedChangePropagation` method receives the propagates ones.

**Review by JanWittler — APPROVED** [review]

**Comment by HeikoKlare** [comment]
Checks link to false application validation action run. The proper one is this, which succeeds:
https://github.com/vitruv-tools/Vitruv-Change/runs/7021814067

**Pull request merged**
